/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PrizeProgressService } from "../prizeProgress.service";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PrizeProgressFindManyArgs } from "./PrizeProgressFindManyArgs";
import { PrizeProgress } from "./PrizeProgress";
import { PrizeProgressWhereUniqueInput } from "./PrizeProgressWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PrizeProgressControllerBase {
  constructor(
    protected readonly service: PrizeProgressService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PrizeProgress] })
  @ApiNestedQuery(PrizeProgressFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PrizeProgress",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async prizeProgresses(
    @common.Req() request: Request
  ): Promise<PrizeProgress[]> {
    const args = plainToClass(PrizeProgressFindManyArgs, request.query);
    return this.service.prizeProgresses({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        datePurchased: true,

        kid: {
          select: {
            id: true,
          },
        },

        prize: {
          select: {
            id: true,
          },
        },

        status: true,
        dateRedeemed: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PrizeProgress })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PrizeProgress",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async prizeProgress(
    @common.Param() params: PrizeProgressWhereUniqueInput
  ): Promise<PrizeProgress | null> {
    const result = await this.service.prizeProgress({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        datePurchased: true,

        kid: {
          select: {
            id: true,
          },
        },

        prize: {
          select: {
            id: true,
          },
        },

        status: true,
        dateRedeemed: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }
}
